### ISSUE TITLE
Why not WASM?

### ISSUE THREAD

**Issue by 0zAND1z** [etclabscore/evm_llvm#10]
Why not use WASM as the execution environment for these LLVM languages?

Just curious.

BTW, nice work! Congrats! 🤠

**Comment by shanejonas** [comment]
ETC has no plans to move its VM to WASM at the moment.

**Comment by 0zAND1z** [comment]
Thanks. Is there an open thread on this discussion within the ETC community?

Would love to contribute to help weight out the pros and cons.

**Comment by lialan** [comment]
> Thanks. Is there an open thread on this discussion within the ETC community?
> 
> Would love to contribute to help weight out the pros and cons.

@0zAND1z 
Thanks buddy for the question. Perhaps we can move to ETC's Discord channel to discuss such question. More people are there too!

link: https://discordapp.com/invite/S9AT3X2

BTW, we are investigating WASM as well, so far there is nothing we can tell. We think that having a LLVM backend for current infrastructure is still necessary.
